#!/usr/bin/env python3
"""Sync data/talks.toml from the public chvancooten/conferences repository.

Usage:
  python3 scripts/sync_talks.py [--repo OWNER/NAME] [--out data/talks.toml]
                                [--overrides data/talks_overrides.toml]

Every top-level folder of the repository is one appearance, named "YYYY-MM - Title @ Event". For each folder:
- date, title and event come from the name. The event drops a trailing year (the date gives it) and spells
  x33fcon one way; an event that mentions "livestream" is marked livestream = true;
- video is the first YouTube link (youtube.com/watch?v= or youtu.be/) in the folder's README.md, if it has one;
- url is the folder on GitHub;
- fields in the overrides file, a table per folder name, replace or add to the above (featured = true, a title or
  event fix, video = "" to drop a link, skip = true to leave the folder out).

The output is deterministic: newest first (folders of the same month by name), a fixed key order and a header
that marks the file as generated. The file is only rewritten when its content changes.

The GitHub API is read with GITHUB_TOKEN when it is set (60 requests an hour without it; a run takes three API
requests, plus one raw download per README). Standard library only.

Exit status: 0 when the file is unchanged or updated; 1 on a fetch or parse error, which leaves the file as it was.
"""

import argparse
import json
import os
import re
import sys
import tempfile
import time
import tomllib
import urllib.error
import urllib.parse
import urllib.request

sys.dont_write_bytecode = True  # keep scripts/ free of __pycache__

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
API = "https://api.github.com"
RAW = "https://raw.githubusercontent.com"
UA = "casvancooten.com sync_talks.py"
TIMEOUT, ATTEMPTS = 20, 3

FOLDER = re.compile(r"(\d{4})-(0[1-9]|1[0-2]) - (.+?) @ (.+)")  # used with fullmatch
YOUTUBE = re.compile(
    r"https?://(?:(?:www\.|m\.)?youtube\.com/watch\?(?:[^\s)\]>\"'<]*&)?v=|youtu\.be/)[A-Za-z0-9_-]{6,}[^\s)\]>\"'<]*")
OVERRIDE_TYPES = {"date": str, "title": str, "event": str, "video": str, "url": str,
                  "featured": bool, "livestream": bool, "skip": bool}
KEYS = ("date", "title", "event", "livestream", "featured", "url", "video")

HEADER = """\
# Conference talks and workshops, newest first.
# Generated by scripts/sync_talks.py from https://github.com/{repo}: the folder names
# ("YYYY-MM - Title @ Event") and the first YouTube link in each folder's README.md. Do not edit this file by
# hand; manual fields go in data/talks_overrides.toml, keyed by folder name.
# event: the event without its year (the date gives it). livestream = true: listed on the home page only when there
# is room. featured = true: always listed on the home page. video: the recording.
"""


class SyncError(Exception):
    pass


def fetch(url, accept=None, token=None):
    """GET url and return the body as text; retries network errors and 5xx responses."""
    headers = {"User-Agent": UA}
    if accept:
        headers["Accept"] = accept
    if token:
        headers["Authorization"] = f"Bearer {token}"
        headers["X-GitHub-Api-Version"] = "2022-11-28"
    for attempt in range(1, ATTEMPTS + 1):
        try:
            with urllib.request.urlopen(urllib.request.Request(url, headers=headers), timeout=TIMEOUT) as resp:
                return resp.read().decode("utf-8")
        except urllib.error.HTTPError as err:
            if err.code >= 500 and attempt < ATTEMPTS:
                time.sleep(2 * attempt)
                continue
            hint = ""
            if err.code in (403, 429) and err.headers.get("X-RateLimit-Remaining") == "0":
                hint = " (API rate limit reached; set GITHUB_TOKEN)"
            raise SyncError(f"GET {url}: HTTP {err.code}{hint}") from None
        except (urllib.error.URLError, TimeoutError, OSError) as err:
            if attempt < ATTEMPTS:
                time.sleep(2 * attempt)
                continue
            raise SyncError(f"GET {url}: {getattr(err, 'reason', err)}") from None
    raise SyncError(f"GET {url}: failed")  # not reached


def api(path, token):
    try:
        return json.loads(fetch(API + path, "application/vnd.github+json", token))
    except json.JSONDecodeError as err:
        raise SyncError(f"GET {API}{path}: invalid JSON ({err})") from None


def shown(path):
    """A path for messages: relative to the repository root when it is inside it, absolute otherwise."""
    path = os.path.abspath(path)
    rel = os.path.relpath(path, ROOT)
    return path if rel == os.pardir or rel.startswith(os.pardir + os.sep) else rel


def normalize_event(event):
    event = re.sub(r"\s+(?:19|20)\d{2}$", "", event.strip())
    return re.sub(r"(?i)\bx33fcon\b", "x33fcon", event)


def parse_folder(name):
    m = FOLDER.fullmatch(name)
    if not m:
        raise SyncError(f'folder {json.dumps(name)} does not match "YYYY-MM - Title @ Event" '
                        '(add skip = true for it in the overrides file to leave it out)')
    year, month, title, event = m.groups()
    event = normalize_event(event)
    talk = {"date": f"{year}-{month}", "title": title.strip(), "event": event}
    if "livestream" in event.lower():
        talk["livestream"] = True
    return talk


def first_youtube_link(markdown):
    m = YOUTUBE.search(markdown)
    return m.group(0).rstrip(".,;:!?") if m else None


def load_overrides(path):
    if not os.path.exists(path):
        return {}
    try:
        with open(path, "rb") as fh:
            data = tomllib.load(fh)
    except tomllib.TOMLDecodeError as err:
        raise SyncError(f"{path}: {err}") from None
    for folder, fields in data.items():
        if not isinstance(fields, dict):
            raise SyncError(f'{path}: "{folder}" must be a table of fields')
        for key, value in fields.items():
            want = OVERRIDE_TYPES.get(key)
            if want is None:
                raise SyncError(f'{path}: "{folder}": unknown field "{key}" '
                                f"(allowed: {', '.join(sorted(OVERRIDE_TYPES))})")
            if not isinstance(value, want):
                raise SyncError(f'{path}: "{folder}": {key} must be a {want.__name__}')
        if "date" in fields and not re.fullmatch(r"\d{4}-(0[1-9]|1[0-2])", fields["date"]):
            raise SyncError(f'{path}: "{folder}": date must be YYYY-MM')
    return data


def collect(repo, token):
    """[(folder name, talk dict)] from the repository's default branch."""
    branch = api(f"/repos/{repo}", token).get("default_branch")
    if not isinstance(branch, str) or not branch:
        raise SyncError(f"{repo}: no default branch in the API response")
    sha = api(f"/repos/{repo}/commits/{urllib.parse.quote(branch, safe='')}", token).get("sha")
    if not isinstance(sha, str) or not re.fullmatch(r"[0-9a-f]{40}", sha):
        raise SyncError(f"{repo}: could not resolve {branch} to a commit")
    tree = api(f"/repos/{repo}/git/trees/{sha}?recursive=1", token)
    if tree.get("truncated"):
        raise SyncError(f"{repo}: the tree listing is truncated")
    entries = tree.get("tree")
    if not isinstance(entries, list):
        raise SyncError(f"{repo}: no tree in the API response")
    folders = sorted(e["path"] for e in entries if e.get("type") == "tree" and "/" not in e.get("path", "/"))
    readmes = {}
    for e in entries:
        path = e.get("path", "")
        if e.get("type") == "blob" and path.count("/") == 1:
            folder, file = path.split("/")
            if file.lower() == "readme.md":
                readmes[folder] = path
    talks = []
    for folder in folders:
        talk = {"folder": folder}
        talk["url"] = f"https://github.com/{repo}/tree/{urllib.parse.quote(branch)}/{urllib.parse.quote(folder, safe='')}"
        if folder in readmes:
            raw = f"{RAW}/{repo}/{sha}/{urllib.parse.quote(readmes[folder])}"
            link = first_youtube_link(fetch(raw))
            if link:
                talk["video"] = link
        talks.append(talk)
    return talks


def build(talks, overrides, overrides_path):
    out = []
    seen = set()
    for t in talks:
        folder = t.pop("folder")
        fields = overrides.get(folder, {})
        seen.add(folder)
        if fields.get("skip"):
            continue
        # A folder whose name does not parse can still be listed when the overrides give date, title and event.
        complete = all(k in fields for k in ("date", "title", "event"))
        talk = {} if complete else parse_folder(folder)
        talk.update(t)
        talk.update({k: v for k, v in fields.items() if k != "skip"})
        for key in ("featured", "livestream"):
            if talk.get(key) is False:
                del talk[key]
        if talk.get("video") == "":
            del talk["video"]
        talk["_folder"] = folder
        out.append(talk)
    for folder in sorted(set(overrides) - seen):
        print(f"sync_talks: warning: {overrides_path}: no folder {json.dumps(folder)} in the repository", file=sys.stderr)
    out.sort(key=lambda t: t["_folder"])
    out.sort(key=lambda t: t["date"], reverse=True)
    return out


def toml_string(s):
    escapes = {"\\": "\\\\", '"': '\\"', "\b": "\\b", "\t": "\\t", "\n": "\\n", "\f": "\\f", "\r": "\\r"}
    return '"' + "".join(escapes.get(c, f"\\u{ord(c):04x}" if ord(c) < 0x20 or ord(c) == 0x7F else c)
                         for c in s) + '"'


def render(talks, repo):
    lines = [HEADER.format(repo=repo)]
    for talk in talks:
        lines.append("[[talks]]")
        for key in KEYS:
            if key not in talk:
                continue
            value = talk[key]
            lines.append(f"{key} = {'true' if value is True else toml_string(value)}")
        lines.append("")
    return "\n".join(lines)


def check_rendered(text, talks):
    """The rendered file must parse back to exactly the synced talks, so Hugo never gets a file it cannot read."""
    want = [{k: t[k] for k in KEYS if k in t} for t in talks]
    try:
        got = tomllib.loads(text).get("talks")
    except tomllib.TOMLDecodeError as err:
        raise SyncError(f"the rendered file is not valid TOML ({err})") from None
    if got != want:
        raise SyncError("the rendered file does not parse back to the synced talks")


def write_if_changed(path, text):
    try:
        with open(path, encoding="utf-8") as fh:
            if fh.read() == text:
                return False
    except FileNotFoundError:
        pass
    fd, tmp = tempfile.mkstemp(dir=os.path.dirname(path) or ".", prefix=".talks-", suffix=".toml")
    try:
        with os.fdopen(fd, "w", encoding="utf-8", newline="\n") as fh:
            fh.write(text)
        os.replace(tmp, path)
    except BaseException:
        os.unlink(tmp)
        raise
    return True


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--repo", default="chvancooten/conferences", help="OWNER/NAME (default: %(default)s)")
    ap.add_argument("--out", default=os.path.join(ROOT, "data", "talks.toml"))
    ap.add_argument("--overrides", default=os.path.join(ROOT, "data", "talks_overrides.toml"))
    args = ap.parse_args(argv)
    if not re.fullmatch(r"[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+", args.repo):
        ap.error("--repo must be OWNER/NAME")
    token = os.environ.get("GITHUB_TOKEN") or None
    try:
        overrides = load_overrides(args.overrides)
        talks = build(collect(args.repo, token), overrides, shown(args.overrides))
        if not talks:
            raise SyncError(f"{args.repo}: no talks found")
        text = render(talks, args.repo)
        check_rendered(text, talks)
        changed = write_if_changed(args.out, text)
    except SyncError as err:
        print(f"sync_talks: error: {err}", file=sys.stderr)
        return 1
    videos = sum(1 for t in talks if "video" in t)
    print(f"sync_talks: {len(talks)} talks, {videos} with a recording; "
          f"{shown(args.out)} {'updated' if changed else 'unchanged'}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
