#!/usr/bin/env python3
"""Sync data/talks.toml from the public chvancooten/conferences repository.

Usage:
  python3 scripts/sync_talks.py [--repo OWNER/NAME] [--out data/talks.toml]
                                [--overrides data/talks_overrides.toml]

Every top-level folder of the repository is one appearance, named "YYYY-MM - Title @ Event". For each folder:
- date, title and event come from the name. The event drops a trailing year (the date gives it) and spells
  x33fcon one way; an event that mentions "livestream" is marked livestream = true;
- video is the first YouTube link in the folder's README.md, if it has one: https on youtube.com/watch?v=<id>
  (also www. and m.) or youtu.be/<id>, with a valid 11-character video id. It is written back in that form, without
  other parameters; trailing punctuation or Markdown around the link is ignored, and http links are not taken;
- url is the folder on GitHub;
- fields in the overrides file, a table per folder name, replace or add to the above (featured = true, a title or
  event fix, video = "" to drop a link, skip = true to leave the folder out). A video or url override is held to the
  same rules (url: https://github.com/...).

Folders whose names start with "." (such as .github) are not talks and are ignored. A folder name with control or
bidirectional formatting characters, or with an empty title or event, is an error.

The output is deterministic: newest first (folders of the same month by name), a fixed key order and a header
that marks the file as generated. The file is only rewritten when its content changes.

The GitHub API is read with GITHUB_TOKEN when it is set (60 requests an hour without it; a run takes three API
requests, plus one raw download per README). Standard library only.

Responses over 1 MB are refused. Exit status: 0 when the file is unchanged or updated; 1 on a fetch or parse error,
which leaves the file as it was.
"""

import argparse
import http.client
import json
import os
import re
import sys
import tempfile
import time
import tomllib
import unicodedata
import urllib.error
import urllib.parse
import urllib.request

sys.dont_write_bytecode = True  # keep scripts/ free of __pycache__

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
API = "https://api.github.com"
RAW = "https://raw.githubusercontent.com"
UA = "casvancooten.com sync_talks.py"
TIMEOUT, ATTEMPTS = 20, 3
MAX_BYTES = 1_000_000  # per response

# ASCII digits only ([0-9], not \d): Hugo has to parse the date.
FOLDER = re.compile(r"([0-9]{4})-(0[1-9]|1[0-2]) - (.+?) @ (.+)")  # used with fullmatch
DATE = re.compile(r"[0-9]{4}-(0[1-9]|1[0-2])")
LINK = re.compile(r"https://\S+")  # candidates; each one is then checked by youtube_url()
VIDEO_ID = re.compile(r"[A-Za-z0-9_-]{11}")
WATCH_HOSTS = ("youtube.com", "www.youtube.com", "m.youtube.com")
TRAIL = "*_~`'\")]}>.,;:!?"  # Markdown and punctuation that can follow a link
# Characters a name must not contain: controls, bidirectional and other format characters, line separators.
BAD_CATEGORIES = {"Cc", "Cf", "Zl", "Zp"}
OVERRIDE_TYPES = {"date": str, "title": str, "event": str, "video": str, "url": str,
                  "featured": bool, "livestream": bool, "skip": bool}
KEYS = ("date", "title", "event", "livestream", "featured", "url", "video")

HEADER = """\
# Conference talks and workshops, newest first.
# Generated by scripts/sync_talks.py from https://github.com/{repo}: the folder names
# ("YYYY-MM - Title @ Event") and the first YouTube link in each folder's README.md. Do not edit this file by
# hand; manual fields go in data/talks_overrides.toml, keyed by folder name.
# event: the event without its year (the date gives it). livestream = true: listed on the home page only when there
# is room. featured = true: always listed on the home page. video: the recording.
"""


class SyncError(Exception):
    pass


def fetch(url, accept=None, token=None):
    """GET url and return the body as text (invalid UTF-8 replaced); retries network errors and 5xx responses.
    The token is never sent on to a redirect target, and a body over MAX_BYTES is an error."""
    headers = {"User-Agent": UA}
    if accept:
        headers["Accept"] = accept
    if token:
        headers["X-GitHub-Api-Version"] = "2022-11-28"
    for attempt in range(1, ATTEMPTS + 1):
        req = urllib.request.Request(url, headers=headers)
        if token:
            req.add_unredirected_header("Authorization", f"Bearer {token}")
        try:
            with urllib.request.urlopen(req, timeout=TIMEOUT) as resp:
                body = resp.read(MAX_BYTES + 1)
                if len(body) <= MAX_BYTES and resp.length:  # fewer bytes than the Content-Length announced
                    raise http.client.IncompleteRead(body, resp.length)
            if len(body) > MAX_BYTES:
                raise SyncError(f"GET {url}: the response is over {MAX_BYTES} bytes")
            return body.decode("utf-8", errors="replace")
        except urllib.error.HTTPError as err:
            if err.code >= 500 and attempt < ATTEMPTS:
                time.sleep(2 * attempt)
                continue
            hint = ""
            if err.code in (403, 429) and err.headers.get("X-RateLimit-Remaining") == "0":
                hint = " (API rate limit reached; set GITHUB_TOKEN)"
            raise SyncError(f"GET {url}: HTTP {err.code}{hint}") from None
        except (urllib.error.URLError, TimeoutError, OSError, http.client.HTTPException) as err:
            if attempt < ATTEMPTS:
                time.sleep(2 * attempt)
                continue
            raise SyncError(f"GET {url}: {getattr(err, 'reason', err)}") from None
    raise SyncError(f"GET {url}: failed")  # not reached


def api(path, token):
    try:
        data = json.loads(fetch(API + path, "application/vnd.github+json", token))
    except json.JSONDecodeError as err:
        raise SyncError(f"GET {API}{path}: invalid JSON ({err})") from None
    if not isinstance(data, dict):
        raise SyncError(f"GET {API}{path}: expected a JSON object")
    return data


def shown(path):
    """A path for messages: relative to the repository root when it is inside it, absolute otherwise."""
    path = os.path.abspath(path)
    rel = os.path.relpath(path, ROOT)
    return path if rel == os.pardir or rel.startswith(os.pardir + os.sep) else rel


def normalize_event(event):
    event = re.sub(r"\s+(?:19|20)[0-9]{2}$", "", event.strip())
    return re.sub(r"(?i)\bx33fcon\b", "x33fcon", event)


def printable(text):
    """text for a log line: control, format and separator characters escaped, so a message stays one line (and a
    name can never start a line with a CI workflow command)."""
    return "".join(f"\\u{ord(c):04x}" if unicodedata.category(c) in BAD_CATEGORIES else c for c in str(text))


def bad_char(text):
    """The first control, bidirectional/format or line-separator character in text, or None."""
    return next((c for c in text if unicodedata.category(c) in BAD_CATEGORIES), None)


def parse_folder(name):
    c = bad_char(name)
    if c is not None:
        raise SyncError(f"folder {json.dumps(name)} contains the character U+{ord(c):04X}, which a name may not contain "
                        "(rename the folder, or add skip = true for it in the overrides file)")
    m = FOLDER.fullmatch(name)
    if not m:
        raise SyncError(f'folder {json.dumps(name)} does not match "YYYY-MM - Title @ Event" '
                        '(add skip = true for it in the overrides file to leave it out)')
    year, month, title, event = m.groups()
    title, event = title.strip(), normalize_event(event)
    if not title or not event:
        raise SyncError(f"folder {json.dumps(name)} has an empty title or event")
    talk = {"date": f"{year}-{month}", "title": title, "event": event}
    if "livestream" in event.lower():
        talk["livestream"] = True
    return talk


def youtube_url(link):
    """The canonical https URL of a YouTube video link, or None if link is not one. Accepted: https on youtube.com,
    www.youtube.com or m.youtube.com with /watch?v=<id>, or youtu.be/<id>, where <id> is a valid video id; Markdown
    or punctuation after the id is ignored, and so are other parameters."""
    try:
        u = urllib.parse.urlsplit(link)
    except ValueError:
        return None
    host = u.netloc.lower()  # the whole netloc: no user info, no port
    if u.scheme != "https":
        return None
    if host == "youtu.be":
        candidate = u.path[1:]
    elif host in WATCH_HOSTS and u.path == "/watch":
        values = urllib.parse.parse_qs(u.query).get("v")
        candidate = values[0] if values else ""
    else:
        return None
    vid, rest = candidate[:11], candidate[11:]
    if not VIDEO_ID.fullmatch(vid) or rest.strip(TRAIL):
        return None
    return f"https://youtu.be/{vid}" if host == "youtu.be" else f"https://{host}/watch?v={vid}"


def first_youtube_link(markdown):
    for m in LINK.finditer(markdown):
        url = youtube_url(m.group(0))
        if url:
            return url
    return None


def github_url(url):
    """True for an https://github.com/... URL without spaces, quotes, angle brackets or control characters."""
    try:
        u = urllib.parse.urlsplit(url)
    except ValueError:
        return False
    return (u.scheme == "https" and u.netloc == "github.com" and u.path.startswith("/")
            and not re.search(r"[\s\"'<>`\\]", url) and bad_char(url) is None)


def load_overrides(path):
    if not os.path.exists(path):
        return {}
    try:
        with open(path, "rb") as fh:
            data = tomllib.load(fh)
    except tomllib.TOMLDecodeError as err:
        raise SyncError(f"{path}: {err}") from None
    for folder, fields in data.items():
        if not isinstance(fields, dict):
            raise SyncError(f'{path}: "{folder}" must be a table of fields')
        for key, value in fields.items():
            want = OVERRIDE_TYPES.get(key)
            if want is None:
                raise SyncError(f'{path}: "{folder}": unknown field "{key}" '
                                f"(allowed: {', '.join(sorted(OVERRIDE_TYPES))})")
            if not isinstance(value, want):
                raise SyncError(f'{path}: "{folder}": {key} must be a {want.__name__}')
        if "date" in fields and not DATE.fullmatch(fields["date"]):
            raise SyncError(f'{path}: "{folder}": date must be YYYY-MM')
        for key in ("title", "event"):
            if key in fields and (not fields[key].strip() or bad_char(fields[key]) is not None):
                raise SyncError(f'{path}: "{folder}": {key} must not be empty or contain control or bidirectional '
                                "formatting characters")
        if fields.get("video"):
            video = youtube_url(fields["video"])
            if not video:
                raise SyncError(f'{path}: "{folder}": video must be an https YouTube video link '
                                "(youtube.com/watch?v=<id> or youtu.be/<id>), or \"\" for none")
            fields["video"] = video
        if "url" in fields and not github_url(fields["url"]):
            raise SyncError(f'{path}: "{folder}": url must be an https://github.com/ URL')
    return data


def collect(repo, token):
    """[(folder name, talk dict)] from the repository's default branch."""
    branch = api(f"/repos/{repo}", token).get("default_branch")
    if not isinstance(branch, str) or not branch:
        raise SyncError(f"{repo}: no default branch in the API response")
    sha = api(f"/repos/{repo}/commits/{urllib.parse.quote(branch, safe='')}", token).get("sha")
    if not isinstance(sha, str) or not re.fullmatch(r"[0-9a-f]{40}", sha):
        raise SyncError(f"{repo}: could not resolve {branch} to a commit")
    tree = api(f"/repos/{repo}/git/trees/{sha}?recursive=1", token)
    if tree.get("truncated"):
        raise SyncError(f"{repo}: the tree listing is truncated")
    entries = tree.get("tree")
    if not isinstance(entries, list):
        raise SyncError(f"{repo}: no tree in the API response")
    folders, readmes = [], {}
    for e in entries:
        if not isinstance(e, dict) or not isinstance(e.get("path"), str) or not isinstance(e.get("type"), str):
            raise SyncError(f"{repo}: unexpected entry in the tree listing")
        path, kind = e["path"], e["type"]
        if path.startswith("."):
            continue  # .github and other dot folders are not talks
        if kind == "tree" and "/" not in path:
            folders.append(path)
        elif kind == "blob" and path.count("/") == 1:
            folder, file = path.split("/")
            if file.lower() == "readme.md":
                readmes[folder] = path
    folders.sort()
    talks = []
    for folder in folders:
        talk = {"folder": folder}
        talk["url"] = f"https://github.com/{repo}/tree/{urllib.parse.quote(branch)}/{urllib.parse.quote(folder, safe='')}"
        if folder in readmes:
            raw = f"{RAW}/{repo}/{sha}/{urllib.parse.quote(readmes[folder])}"
            link = first_youtube_link(fetch(raw))
            if link:
                talk["video"] = link
        talks.append(talk)
    return talks


def build(talks, overrides, overrides_path):
    out = []
    seen = set()
    for t in talks:
        folder = t.pop("folder")
        fields = overrides.get(folder, {})
        seen.add(folder)
        if fields.get("skip"):
            continue
        # A folder whose name does not parse can still be listed when the overrides give date, title and event.
        complete = all(k in fields for k in ("date", "title", "event"))
        talk = {} if complete else parse_folder(folder)
        talk.update(t)
        talk.update({k: v for k, v in fields.items() if k != "skip"})
        for key in ("featured", "livestream"):
            if talk.get(key) is False:
                del talk[key]
        if talk.get("video") == "":
            del talk["video"]
        # Backstops: every link that reaches the site is one of these two kinds.
        if not github_url(talk.get("url", "")):
            raise SyncError(f"folder {json.dumps(folder)}: url is not an https://github.com/ URL")
        if "video" in talk and youtube_url(talk["video"]) != talk["video"]:
            raise SyncError(f"folder {json.dumps(folder)}: video is not a canonical YouTube link")
        talk["_folder"] = folder
        out.append(talk)
    for folder in sorted(set(overrides) - seen):
        print(printable(f"sync_talks: warning: {overrides_path}: no folder {json.dumps(folder)} in the repository"),
              file=sys.stderr)
    out.sort(key=lambda t: t["_folder"])
    out.sort(key=lambda t: t["date"], reverse=True)
    return out


def toml_string(s):
    escapes = {"\\": "\\\\", '"': '\\"', "\b": "\\b", "\t": "\\t", "\n": "\\n", "\f": "\\f", "\r": "\\r"}
    return '"' + "".join(escapes.get(c, f"\\u{ord(c):04x}" if ord(c) < 0x20 or ord(c) == 0x7F else c)
                         for c in s) + '"'


def render(talks, repo):
    lines = [HEADER.format(repo=repo)]
    for talk in talks:
        lines.append("[[talks]]")
        for key in KEYS:
            if key not in talk:
                continue
            value = talk[key]
            lines.append(f"{key} = {'true' if value is True else toml_string(value)}")
        lines.append("")
    return "\n".join(lines)


def check_rendered(text, talks):
    """The rendered file must parse back to exactly the synced talks, so Hugo never gets a file it cannot read."""
    want = [{k: t[k] for k in KEYS if k in t} for t in talks]
    try:
        got = tomllib.loads(text).get("talks")
    except tomllib.TOMLDecodeError as err:
        raise SyncError(f"the rendered file is not valid TOML ({err})") from None
    if got != want:
        raise SyncError("the rendered file does not parse back to the synced talks")


def write_if_changed(path, text):
    try:
        with open(path, encoding="utf-8") as fh:
            if fh.read() == text:
                return False
    except FileNotFoundError:
        pass
    fd, tmp = tempfile.mkstemp(dir=os.path.dirname(path) or ".", prefix=".talks-", suffix=".toml")
    try:
        with os.fdopen(fd, "w", encoding="utf-8", newline="\n") as fh:
            fh.write(text)
        os.replace(tmp, path)
    except BaseException:
        os.unlink(tmp)
        raise
    return True


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--repo", default="chvancooten/conferences", help="OWNER/NAME (default: %(default)s)")
    ap.add_argument("--out", default=os.path.join(ROOT, "data", "talks.toml"))
    ap.add_argument("--overrides", default=os.path.join(ROOT, "data", "talks_overrides.toml"))
    args = ap.parse_args(argv)
    if not re.fullmatch(r"[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+", args.repo):
        ap.error("--repo must be OWNER/NAME")
    token = os.environ.get("GITHUB_TOKEN") or None
    try:
        overrides = load_overrides(args.overrides)
        talks = build(collect(args.repo, token), overrides, shown(args.overrides))
        if not talks:
            raise SyncError(f"{args.repo}: no talks found")
        text = render(talks, args.repo)
        check_rendered(text, talks)
        changed = write_if_changed(args.out, text)
    except SyncError as err:
        print(printable(f"sync_talks: error: {err}"), file=sys.stderr)
        return 1
    except (ValueError, KeyError, AttributeError, TypeError) as err:  # an API response of an unexpected shape
        print(printable(f"sync_talks: error: unexpected data ({type(err).__name__}: {err})"), file=sys.stderr)
        return 1
    videos = sum(1 for t in talks if "video" in t)
    print(f"sync_talks: {len(talks)} talks, {videos} with a recording; "
          f"{shown(args.out)} {'updated' if changed else 'unchanged'}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
